class SourceArea < ActiveHash::Base
  include ActiveHash::Associations
  has_many :items

  field :name
  add id: 1, name: "北海道"
  add id: 2, name: "青森県"
  add id: 3, name: "岩手県"
  add id: 4, name: "宮城県"
  add id: 5, name: "秋田県"
  add id: 6, name: "山形県"
  add id: 7, name: "福島県"
  add id: 8, name: "茨城県"
  add id: 9, name: "栃木県"
  add id: 10, name: "群馬県"
  add id: 11, name: "埼玉県"
  add id: 12, name: "千葉県"
  add id: 13, name: "東京都"
  add id: 14, name: "神奈川県"
  add id: 15, name: "新潟県"
  add id: 16, name: "富山県"
  add id: 17, name: "石川県"
  add id: 18, name: "福井県"
  add id: 19, name: "山梨県"
  add id: 20, name: "長野県"
  add id: 21, name: "岐阜県"
  add id: 22, name: "静岡県"
  add id: 23, name: "愛知県"
  add id: 24, name: "三重県"
  add id: 25, name: "滋賀県"
  add id: 26, name: "京都府"
  add id: 27, name: "大阪府"
  add id: 28, name: "兵庫県"
  add id: 29, name: "奈良県"
  add id: 30, name: "和歌山県"
  add id: 31, name: "鳥取県"
  add id: 32, name: "島根県"
  add id: 33, name: "岡山県"
  add id: 34, name: "広島県"
  add id: 35, name: "山口県"
  add id: 36, name: "徳島県"
  add id: 37, name: "香川県"
  add id: 38, name: "愛媛県"
  add id: 39, name: "高知県"
  add id: 40, name: "佐賀県"
  add id: 41, name: "福岡県"
  add id: 42, name: "長崎県"
  add id: 43, name: "熊本県"
  add id: 44, name: "大分県"
  add id: 45, name: "宮崎県"
  add id: 46, name: "鹿児島県"
  add id: 47, name: "沖縄県"
  add id: 48, name: "未定"
end